version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user_password
      WORDPRESS_DB_NAME: nhaxemyduyen
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    depends_on:
      - db
      

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"  # ADD THIS LINE TO EXPOSE MYSQL PORT
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nhaxemyduyen
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_nhaxemyduyen:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    restart: always

volumes:
  wordpress_data:
  db_nhaxemyduyen: